### ISSUE TITLE
Expose more options to configure the text font from "TableCellStyleBuilder"

### ISSUE THREAD

**Issue by negora** [jferard/fastods#139] opened 2019-03-22 10:45 UTC
The `TableCellStyleBuilder` allows to build a `TableCellStyle`. But I've realized that it lacks some options for the text font configuration, such as name (family) and size.

Checking the source code of `TableCellStyleBuilder`, I've seen that it uses an instance of `TextPropertiesBuilder` to set the options of text font. This class already has methods to configure the name and size of the font. So, Why aren't these exposed by `TableCellStyleBuilder`?

Thank you!

**Comment by jferard** [comment] 2019-03-23 19:43
> So, Why aren't these exposed by TableCellStyleBuilder?

Because nobody asked and I didn't need it! Yet these are among the most useful options for a cell style, hence I'll fix it.

**Comment by negora** [comment] 2019-03-24 20:42
@jferard Thank you! I'll look forward for this feature. I also think that that it's very interesting one.

I've been playing with a local copy of your project, in which I've exposed these features from the `TableCellStyleBuilder` class. However, I've not had luck when setting the font family. I guess that it's not as easy as just re-directing the method calls from one class to the other.

**Comment by jferard** [comment] 2019-03-29 20:05
@negora See the data styles example: https://github.com/jferard/fastods/blob/master/fastods/src/test/java/com/github/jferard/fastods/it/DataStyleExampleIT.java#L138


![font family and size](https://user-images.githubusercontent.com/10564095/55259511-286ec280-5266-11e9-902d-77d18c01effa.png)

**Comment by jferard** [comment] 2019-03-29 20:10
Issue was automatically closed by the commit message. I reopen and let you close it if that's ok for you.

**Comment by negora** [comment] 2019-03-30 08:14
@jferard Thanks a lot. Give me a few days to try it when I'm back at work. I'll answer as soon as possible ;) .

**Comment by negora** [comment] 2019-04-01 09:16
@jferard I've tested the new feature in my code, but it has taken me some time to find out why LibreOffice wasn't interpreting the row height. It was because I wasn't calling the method `TableRowStyleBuilder.hidden()` before building the style. Thanks to your tests I've found the cause.

Why does this happen? I've checked the wiki of FastODS and also this post at `ask.libreoffice.org`: [difference between styles and automatic-styles [closed]](https://ask.libreoffice.org/en/question/32602/difference-between-styles-and-automatic-styles/). But the specification seems to be really complex on this regard :S .

Thank you!

### Some quick thoughts that may deserve their own tickets

**Thought 1:** Because the consequences of declaring a style as `hidden` goes beyond simply hiding such style, I wonder if it would be better to rename the method `hidden()` to `automatic()` or `asAutomatic()`. In a far future, of course. What do you think?

**Thought 2:** The wiki also says that the row styles are visible by default. But, when I open an ODS generated with this library, I cant' see the row style in the list of styles. Regardless I call "TableRowStyleBuilder.hidden()" or not.

**Comment by negora** [comment] 2019-04-01 10:14
@jferard OK, I've just seen that the ticket #142 is already treating this issue with `TableRowStyleBuilder.rowHeight()`. Apologizes for the duplication.

With regard to setting the font size, it seems to work fine :+1: . But, I don't know why, the font family seems to have no effect. I've checked the resulting `style.xml` file (inside of the ODS file), and it has the font family actually registered. But LibreOffice ignores it.

**Comment by jferard** [comment] 2019-04-01 12:31
**Thought 1**: as you stated, the spec is very... hmm... complex and it becomes more complex when I have to stick with LO interpretations of the spec. E.g. styles can go in three different places in the ODS file, but LO will ignore those styles if they are not at the "right" place.

I want to hide this complexity if possible, but that's complex too. I think it's possible to continue with `hidden`/`visible` for now.

**Thought 2**: see my question in #142 (can you provide a minimal example to reproduce the bug).

**Font family**:
1) Simple test: just take the example https://github.com/jferard/fastods/blob/master/fastods/src/test/java/com/github/jferard/fastods/it/DataStyleExampleIT.java#L138 and replace the name of the font by `"DejaVu Sans Mono"`.
2) Do you see the font at the top of the content.xml file, in `<office:font-face-decls>`? If yes, is the font name exact (it seems that's the case)? is the font available on your system?

**Comment by negora** [comment] 2019-04-01 17:15
**Thought 1:** OK. Given the circumstances, that decision seems reasonable.

**Thought 2:** OK. I've answered to the question about the row height in the issue #142.

### About the font family.

I think that I know the cause of my problem. I'm applying the cell style **as the default style for a given column.** I'm doing this:

```java
TableCellStyle cellStyle = TableCellStyle
  .builder ("myCellStyle")
  .fontName ("monospace")
  .fontSize (SimpleLength.pt (18))
  .build ();
  
TableColumnStyle columnStyle = TableColumnStyle
  .builder ("myColumnStyle")
  .defaultCellStyle (cellStyle);
table.setColumnStyle (0, columnStyle);
```

If I do this, the font family is not set correctly. It appears in the file `style.xml`, but it doesn't appear in the`<office:font-face-decls>` element of the `content.xml` file.

By contrast, if I apply the cell style directly on the cell, the font family is set properly.

This bug seems to affect the font family option only. Other options applied at the column level, such as font size or background colour, work fine.

**Comment by jferard** [comment] 2019-04-15 19:35
@negora Can you try with the last version?

**Comment by negora** [comment] 2019-05-13 07:41
Sorry for the delay, but I've been away from work.

I've just tested my application against your last version, and the font family seems to be applied correctly now :+1: .

**Comment by jferard** [comment] 2019-05-13 15:20
Ok. I close the issue. Feel free to re-open if necessary.

**Closed by jferard** 2019-05-13 15:20 UTC
Labels: enhancement
