### ISSUE TITLE
TableRowStyle rowHeight does not work

### ISSUE THREAD

**Issue by qmor** [jferard/fastods#142] opened 2019-03-24 08:02 UTC
Hi. I'm trying to set forst row height using TableRowStyle like this:

 
 ```table.getRow(0).setStyle(TableRowStyle.builder("firstrowstyle").rowHeight(SimpleLength.mm(100)).build());```

but LibreOffice (6.2.0.3) ignore it.

**Comment by jferard** [comment] 2019-03-24 09:08
Hi. I will investigate this.

**Comment by jferard** [comment] 2019-03-26 20:18
@qmor Can you try with:

```table.getRow(0).setStyle(TableRowStyle.builder("firstrowstyle").rowHeight(SimpleLength.mm(100)).hidden().build());```
    
? `hidden()` for an automatic style, that is a style that does not appear in the style panel.

It does not solve the issue, but it may help you.

**Comment by qmor** [comment] 2019-03-27 04:44
Have tried, but without any effect.

**Comment by fanboy1016** [comment] 2019-03-28 06:00
0.6.1-SNAPSHOT
hidden().build()
0.6.0 
buildHidden()
All not work

**Comment by jferard** [comment] 2019-03-29 20:09
@qmor and @fanboy1016 
I set the first row height to 25mm in https://github.com/jferard/fastods/blob/master/fastods/src/test/java/com/github/jferard/fastods/it/DataStyleExampleIT.java#L147. Here's the output:

![Some data styles](https://user-images.githubusercontent.com/10564095/55259433-e9407180-5265-11e9-841d-8115f5958422.png)

Can you provide a minimal example that reproduces the bug? Thanks.

**Comment by qmor** [comment] 2019-03-30 07:02
It's so strange but for not i've clean and rebuild project and 

				table.getRow(0).setStyle(TableRowStyle.builder("firstrowstyle").rowHeight(SimpleLength.mm(50)).hidden().build());
works as expected (at least in 6.2.0.3)

Thanks a lot for attention.

**Comment by negora** [comment] 2019-04-01 16:32
The method `TableRowStyle.rowHeight()` seems to work fine. The row height is interpreted correctly by LibreOffice 5.2.7 (the one from the Debian 9 repositories) and by 6.2.2 (the one supplied by The Document Foundation).

In my opinion, the problem seems to be on the LO side. If you don't mark the style as hidden (automatic), LO ignores it completely. I don't know why.

**Comment by jferard** [comment] 2019-06-18 21:18
Just made `TableRowStyle` hidden by default, to avoid issues like that.

**Comment by jferard** [comment] 2019-07-07 12:28
Seems ok now. I close the issue. Reopen it if necessary.

**Comment by GregorySokoloff** [comment] 2019-10-03 04:17
It seems I am having exactly the same problem with v0.7.0 even with the latest LO (Version: 6.3.2.2 (x64)), and Google sheets. I'm not looking forward to tracking down the cause! Any help would be much appreciated. Merci.

P.S. I tested it with a minimal Hello World example with the added setHeight() as above.

**Comment by jferard** [comment] 2019-10-03 18:59
Hi. Can you post your code please?

**Comment by GregorySokoloff** [comment] 2019-10-03 19:17
Thanks for the prompt response. Here's the code:

            OdsFactory odsFactory = OdsFactory.create(Logger.getLogger("hello-world"), Locale.US);
            AnonymousOdsFileWriter writer = odsFactory.createWriter();
            OdsDocument document = writer.document();
            Table table = document.addTable("Worksheet1");

            TableRowImpl row = table.getRow (0);
            row.setRowStyle (TableRowStyle.builder ("my_row_style")
                                          .rowHeight (SimpleLength.cm (2.0)).build ());

            row.getOrCreateCell (0).setStringValue ("Howdy y'all!");

            File file = new File(filesDir, "junk.ods");
            writer.saveAs(file);
```

**Comment by GregorySokoloff** [comment] 2019-10-03 19:18
And here's what LO thinks about my meagre efforts:

![Clipboard01](https://user-images.githubusercontent.com/56102040/66157087-0a0cc980-e5f1-11e9-8f25-2b9b7a8302b4.png)

**Comment by jferard** [comment] 2019-10-03 19:54
I just took your code and got this (no cheat!):

![Capture2019-10-03](https://user-images.githubusercontent.com/10564095/66158279-e152f700-e625-11e9-9675-249ad82bbe5d.png)

My guess is that you have something like the infamous *quickstarter* (now deprecated) running. The quickstarter prevents LO from reloading the full document after update (e.g. the scripts are never reloaded).

Can you check in **Tools > Options > LibreOffice > General**?

Other option: if you are using Windows, you can: 1. close all documents (VERY IMPORTANT IF YOU DON'T WANT TO LOOSE DATA), quit LO and 2. check in the Task Manager if you have a soffice.bin or soffice.exe running (or both) and kill them. Then try to reopen "junk.ods" (no need to recreate it).

**Comment by GregorySokoloff** [comment] 2019-10-03 20:11
Thanks for trying it. The _quickstarter_ option was never checked, and soffice.* was not running in the Task Manager. I'm going to drop my file below to see if you still get so much better service than I from LO! (I have renamed the extension to .zip so that it will be accepted here.)
[junk.zip](https://github.com/jferard/fastods/files/3687869/junk.zip)

**Comment by GregorySokoloff** [comment] 2019-10-03 20:47
Julien,

A couple of other points:
-  My code was running on Android, not that it should make any difference.
- Excel does not like the file at all. It says "We found a problem with some content in 'junk.ods'. Do you want us to try to recover as mush as we can>=?" On clicking yes, then a dialog pops up with: "Excel was able to open the file by repairing or removing the unreadable content." Then it shows the document just like LO with the row height not respected.

Cheers,
Gregory

**Comment by jferard** [comment] 2019-10-03 21:30
I just tried your file: same result as above (it works). My LO version is 6.0.7.3. I'll try with a newer version as soon as possible.

* About Android: you're right, it should not make any difference.
* About Excel: FastODS aims to produce OpenDocument1.2 documents. I try my best to have those documents understood by LO (workarounds are sometimes necessary even if the document is compliant with the norm), but I can't test them with Excel.

**Comment by GregorySokoloff** [comment] 2019-10-03 21:45
Hah! I just downgraded to 6.0.7.3, and, VOILÀ, it works!

**Comment by GregorySokoloff** [comment] 2019-10-03 21:46
It seems that LO is more Bordeaux than Beaujolais: the older vintages are better!

**Comment by jferard** [comment] 2019-10-04 18:23
You're right about wines! I'm happy you found a solution, but I'm interested in the cause that makes newer LO ignore the row height in FastODS files and I will continue to investigate this issue.

**Comment by GregorySokoloff** [comment] 2019-10-04 20:27
I am also very interested in a solution for current versions of LO. I even started to investigate by unzipping an .ods file created by current LO and comparing the content.xml to that produced by FastODS. Not a simple procedure. I hope you can crack the problem.

**Closed** 2019-10-05 12:58 UTC
Labels: bug

**Comment by jferard** [comment] 2019-10-05 13:05
Gregory, seems you found a real bug here! The `style:use-optimal-row-height` was always true and there was a wrong attribute `style:use-optimal-row-width` (I don't know why).
I fixed it and tested with both LO 6.0.7.3 and LO 6.3.2.2. (To be fair, this time LO was a Beaujolais: the new version is better than the old one.)

Can you try the lastest version of FastODS (git clone, mvn clean install)? If it works, can you try to open the file "junk.ods" with Excel? Hope it works.

**Comment by GregorySokoloff** [comment] 2019-10-05 18:24
Cher Julien,

Magnifique! You fixed it.

I rebuilt as per your instructions, and then tried it with the latest
LibreOffice. No problem. Then Google Sheets. No problem. ...

Then Excel. No problems with respecting the row heights. However, it still
complains on loading that, "We found a problem with some content in
'junk.ods'. Do you want us to try to recover as much as we can?" (I hereby
label this the ExcelWhine.) After a little investigation, I have some more
observations to make about Excel:


   1. If you make a completely blank .ods document using FastODS (ie. my
   original test program without setting row height or cell value), Excel
   still ExcelWhines. I conclude that it is very likely that all documents
   created by FastODS will receive the ExcelWhine sobriquet.
   2. A new problem probably completely unrelated to (1) is that Excel does
   not seem to recognize horizontal cell merging from FastODS (though it does
   recognize vertical merges). For example, cell.setCellMerge(2,2) will come
   out in Excel just as setCellMerge(1,2) would.

Do you want me to just shut up about the Excel stuff? Otherwise, I can add
issues to the GitHub project.

Anyway, I am very grateful for your fine work.

Cheers,
Gregory

**Comment by jferard** [comment] 2019-10-05 19:33
Feel free to post Excel related issues. I won't investigate these issues because I do not have Excel, but I'll use the tag "help wanted" and we'll see if someone finds why Excel whines about FastODS files.
If there is an acceptable reason *and if that does not slow the file generation*, I'll try to improve FastODS compatibility with Excel.

**Comment by ueen** [comment] 2020-11-01 12:20
ods files created by Excel open just fine, so maybe thats worth looking into, i provieded an example file created with excel 2016 (sorry had to zip for github to upload)
[test.zip](https://github.com/jferard/fastods/files/5470794/test.zip)

**Comment by ueen** [comment] 2020-11-01 12:45
A few clues, after these modifications Excel accepts the ods produced by fastods: replace styles with this:
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<office:document-styles xmlns:table="urn:oasis:names:tc:opendocument:xmlns:table:1.0" xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0" xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0" xmlns:draw="urn:oasis:names:tc:opendocument:xmlns:drawing:1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:number="urn:oasis:names:tc:opendocument:xmlns:datastyle:1.0" xmlns:svg="urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0" xmlns:of="urn:oasis:names:tc:opendocument:xmlns:of:1.2" office:version="1.2"><office:font-face-decls><style:font-face style:name="Calibri" svg:font-family="Calibri"/></office:font-face-decls><office:styles><number:number-style style:name="N0"><number:number number:min-integer-digits="1"/></number:number-style><style:style style:name="Default" style:family="table-cell" style:data-style-name="N0"><style:table-cell-properties style:vertical-align="automatic" fo:background-color="transparent"/><style:text-properties fo:color="#000000" style:font-name="Calibri" style:font-name-asian="Calibri" style:font-name-complex="Calibri" fo:font-size="11pt" style:font-size-asian="11pt" style:font-size-complex="11pt"/></style:style><style:default-style style:family="graphic"><style:graphic-properties draw:fill="solid" draw:fill-color="#4472c4" draw:opacity="100%" draw:stroke="solid" svg:stroke-width="0.01389in" svg:stroke-color="#2f528f" svg:stroke-opacity="100%" draw:stroke-linejoin="miter" svg:stroke-linecap="butt"/></style:default-style></office:styles><office:automatic-styles><style:page-layout style:name="pm1"><style:page-layout-properties fo:margin-top="0.3in" fo:margin-bottom="0.3in" fo:margin-left="0.7in" fo:margin-right="0.7in" style:table-centering="none" style:print="objects charts drawings"/><style:header-style><style:header-footer-properties fo:min-height="0.487401575in" fo:margin-left="0.7in" fo:margin-right="0.7in" fo:margin-bottom="0in"/></style:header-style><style:footer-style><style:header-footer-properties fo:min-height="0.487401575in" fo:margin-left="0.7in" fo:margin-right="0.7in" fo:margin-top="0in"/></style:footer-style></style:page-layout></office:automatic-styles><office:master-styles><style:master-page style:name="mp1" style:page-layout-name="pm1"><style:header/><style:header-left style:display="false"/><style:footer/><style:footer-left style:display="false"/></style:master-page></office:master-styles></office:document-styles>`
and change content header to this
`<office:document-content xmlns:table="urn:oasis:names:tc:opendocument:xmlns:table:1.0" xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0" xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0" xmlns:draw="urn:oasis:names:tc:opendocument:xmlns:drawing:1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:number="urn:oasis:names:tc:opendocument:xmlns:datastyle:1.0" xmlns:svg="urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0" xmlns:of="urn:oasis:names:tc:opendocument:xmlns:of:1.2" office:version="1.2"><office:font-face-decls><style:font-face style:name="Calibri" svg:font-family="Calibri"/></office:font-face-decls><office:automatic-styles><style:style style:name="ce1" style:family="table-cell" style:parent-style-name="Default" style:data-style-name="N0"/><style:style style:name="co1" style:family="table-column"><style:table-column-properties fo:break-before="auto" style:column-width="2.11666666666667cm"/></style:style><style:style style:name="ro1" style:family="table-row"><style:table-row-properties style:row-height="15pt" style:use-optimal-row-height="true" fo:break-before="auto"/></style:style><style:style style:name="ta1" style:family="table" style:master-page-name="mp1"><style:table-properties table:display="true" style:writing-mode="lr-tb"/></style:style></office:automatic-styles>`
and remove `office:forms` tags

**Comment by ueen** [comment] 2020-11-01 12:54
maybe it would be possible to create a excel mode where these things are considered? This type of ods also works in Google Sheets, can some test in libre office? (sample provided below)
[ahh.zip](https://github.com/jferard/fastods/files/5470847/ahh.zip)

**Comment by jferard** [comment] 2020-11-01 14:42
@ueen Thanks a lot for your suggestion. I'll have a look at this next week.

**Comment by ueen** [comment] 2020-11-01 17:06
further clues: Files with fastods have office:version 1.1, Excel 2016 has 1.2, and Libre Office 7.0 has 1.3 - but that doesnt seem to be much of a difference. simple ODS files created with LibreOffice open just fine in Excel, they dont include the office:forms tag, so i think we can get rid of that.

**Comment by ueen** [comment] 2020-11-01 17:16
The other issue seems to be with office:automatic-styles, specifically with the table style:master-page-name, fastods has `DefaultMasterPage` whereas Libreoffie has `Default` and Excel doesnt have a style:master-page-name.

**Comment by ueen** [comment] 2020-11-01 17:28
Ok so i modified the fastods file like this: i deleted office:forms and changed `DefaultMasterPage `to `Default ` and swaped the styles.xml for the one from a fresh Libreoffice 7.0 file and et voilà is works just fine in Excel 2016 and Libreoffice.
I dont know if these are the best changes or if fastods should be converted to office:version 1.3, which seems to the latest, but i figured that these are the smallest changes that produce the greatest benefit (opening without errors in Excel and LibreOffice Calc).
I'll try to do a PullRequest, but feel free to do the changes yourself, as you probably know your code best.
Another strange behaviour i noticed was the grid was missing for a basic file created with fastods and opend in either Google Sheets, Libreoffice or Excel, i dont know if this is due to missing code or if this is by design, anyway it is fixed when using the new styles.xml
The fresh styles is here (just rename to xml).
[styles.txt](https://github.com/jferard/fastods/files/5471405/styles.txt)

**Comment by ueen** [comment] 2020-11-01 17:49
Actually the styles header is also fine, the content needs to be changed from `<office:font-face-decls`

**Comment by ueen** [comment] 2020-11-01 18:55
`styles.xml`
Actually actually its just the style:master-page style:name that needs to be `Default` - thats the only changes thats required to shut Excel up, but the grids still missing in Libreoffice adn excel

**Comment by ueen** [comment] 2020-11-01 19:15
`styles.xml`
the grid issue is due to the fo:background-color of the default table-cell style, neither LibreOffice nor Excel define that by default, i don't know if theres a special reason, but i'll delete it for now, to solve the grid not showing issue

**Comment by ueen** [comment] 2020-11-01 19:30
OK i think i got it and created a Pull Request, please let me know if any issues persist :)

**Comment by jferard** [comment] 2020-11-02 07:36
@ueen Thanks for the PR. I'll check that this week.
